### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(JourneyOSContent)
add_subdirectory(JourneyOS)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    JourneyOSContentplugin
    JourneyOSplugin)